import "bootstrap/dist/css/bootstrap.min.css";
import Link from "next/link";
import Navbar from "./navbar";

export const metadata = {
  title: "Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>

        <main>{children}</main>
      </body>
    </html>
  );
}
